# Generated by Django 5.2.8 on 2025-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userForName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userMail',
            field=models.EmailField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
