# Generated by Django 5.2.8 on 2025-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_phonenumber_user_userforname_user_usermail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
